on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/cloudflare
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7

      - name: "Set up terraform"
        uses: hashicorp/setup-terraform@v4

      - name: "Format tf files"
        run: terraform fmt -check -recursive

      - name: "Init terraform"
        run: terraform init -backend=false

      - name: "Validate terraform"
        run: terraform validate

      - name: "TF Linter set up"
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.52.0
          cache: true

      - name: "Show version"
        run: tflint --version

      - name: "Init TFlint"
        run: tflint --init

      - name: "Run tflint"
        run: tflint -f compact
      